#ifndef ANSI_H
#define ANSI_H

#define ANSI_RESET "\x1b[0m"
#define ANSI_BOLD "\x1b[1m"
#define ANSI_FAINT "\x1b[2m"
#define ANSI_ITALIC "\x1b[3m"
#define ANSI_UNDERLINE "\x1b[4m"
#define ANSI_BLINK "\x1b[5m"
#define ANSI_BLINK_RAPID "\x1b[6m"
#define ANSI_INVERT "\x1b[7m"
#define ANSI_CONCEAL "\x1b[8m"
#define ANSI_CROSSOUT "\x1b[9m"

#define ANSI_RST_BOLD "\x1b[21m"
#define ANSI_RST_COLOUR "\x1b[22m"
#define ANSI_RST_ITALIC "\x1b[23m"
#define ANSI_RST_UNDERLINE "\x1b[24m"
#define ANSI_RST_BLINK "\x1b[25m"
#define ANSI_RST_INVERT "\x1b[27m"
#define ANSI_RST_CONCEAL "\x1b[28m"
#define ANSI_RST_CROSSOUT "\x1b[29m"

#define ANSI_FG_BLACK "\x1b[30m"
#define ANSI_FG_RED "\x1b[31m"
#define ANSI_FG_GREEN "\x1b[32m"
#define ANSI_FG_YELLOW "\x1b[33m"
#define ANSI_FG_BLUE "\x1b[34m"
#define ANSI_FG_MAGENTA "\x1b[35m"
#define ANSI_FG_CYAN "\x1b[36m"
#define ANSI_FG_WHITE "\x1b[37m"
#define ANSI_FG_DEFAULT "\x1b[39m"

#define ANSI_BG_BLACK "\x1b[40m"
#define ANSI_BG_RED "\x1b[41m"
#define ANSI_BG_GREEN "\x1b[42m"
#define ANSI_BG_YELLOW "\x1b[43m"
#define ANSI_BG_BLUE "\x1b[44m"
#define ANSI_BG_MAGENTA "\x1b[45m"
#define ANSI_BG_CYAN "\x1b[46m"
#define ANSI_BG_WHITE "\x1b[47m"
#define ANSI_BG_DEFAULT "\x1b[49m"

#define ANSI_OVERLINE "\x1b[53m"
#define ANSI_RST_OVERLINE "\x1b[55m"

#define ANSI_FG_HI_BLACK "\x1b[90m"
#define ANSI_FG_HI_RED "\x1b[91m"
#define ANSI_FG_HI_GREEN "\x1b[92m"
#define ANSI_FG_HI_YELLOW "\x1b[93m"
#define ANSI_FG_HI_BLUE "\x1b[94m"
#define ANSI_FG_HI_MAGENTA "\x1b[95m"
#define ANSI_FG_HI_CYAN "\x1b[96m"
#define ANSI_FG_HI_WHITE "\x1b[97m"
#define ANSI_FG_HI_DEFAULT "\x1b[99m"

#define ANSI_BG_HI_BLACK "\x1b[100m"
#define ANSI_BG_HI_RED "\x1b[101m"
#define ANSI_BG_HI_GREEN "\x1b[102m"
#define ANSI_BG_HI_YELLOW "\x1b[103m"
#define ANSI_BG_HI_BLUE "\x1b[104m"
#define ANSI_BG_HI_MAGENTA "\x1b[105m"
#define ANSI_BG_HI_CYAN "\x1b[106m"
#define ANSI_BG_HI_WHITE "\x1b[107m"
#define ANSI_BG_HI_DEFAULT "\x1b[109m"

#endif
